rem Vlozeni testovacich dat do tabulky zakonceni_predmetu
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('KZ','Klasifikovaný zápočet');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('ZK','Zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('KPZ','Klauzurní postupová zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('KP','Klauzurní práce');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('OBP','Obhajoba bakalářské práce');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('ODIP','Obhajoba diplomové práce');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('ODIS','Obhajoba disertační práce');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('OZP','Obhajoba závěrečné práce');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('RP','Rigorózní práce');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('SZ','Souborná zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('SDDZ','Státní dokt. dílčí zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('SDZ','Státní doktorská zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('SPZ','Státní postupová zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('SRZ','Státní rigorózní zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('SZZ','Státní závěrečná zkouška');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('ZP','Zápočet');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('ZZV','Zápočet za VŠKP');
Insert into ZAKONCENI_PREDMETU (ZKRATKAZAKONCENI,NAZEVZAKONCENI) values ('ZZ','Závěrečná zkouška');